import { csvDownloadUrl, dashboardPngUrl, riskMapHtmlUrl } from "../api.js";

function CsvIcon() {
  return (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none">
      <path d="M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z" stroke="currentColor" strokeWidth="1.6" strokeLinejoin="round"/>
      <path d="M14 3v6h6" stroke="currentColor" strokeWidth="1.6" strokeLinejoin="round"/>
      <text x="7" y="18" fontSize="6" fill="currentColor" fontWeight="700" fontFamily="monospace">CSV</text>
    </svg>
  );
}
function ImageIcon() {
  return (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none">
      <rect x="3" y="4" width="18" height="16" rx="2" stroke="currentColor" strokeWidth="1.6"/>
      <circle cx="9" cy="10" r="1.6" fill="currentColor"/>
      <path d="M21 15l-5-5-8 8" stroke="currentColor" strokeWidth="1.6" strokeLinejoin="round"/>
    </svg>
  );
}
function MapIcon() {
  return (
    <svg width="22" height="22" viewBox="0 0 24 24" fill="none">
      <path d="M9 4L3 6v14l6-2 6 2 6-2V4l-6 2-6-2z" stroke="currentColor" strokeWidth="1.6" strokeLinejoin="round"/>
      <path d="M9 4v14M15 6v14" stroke="currentColor" strokeWidth="1.6"/>
    </svg>
  );
}
function DownloadIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none">
      <path d="M12 4v12m0 0l-4-4m4 4l4-4M5 20h14" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  );
}

const DOWNLOADS = [
  {
    name: "crop_census.csv",
    desc: "Fully cleaned crop census output — state, crop, yield, irrigation, rainfall, revenue, and the derived Water_Stressed flag.",
    url: csvDownloadUrl,
    icon: <CsvIcon />,
  },
  {
    name: "agri_dashboard.png",
    desc: "Static four-panel Matplotlib export covering rainfall-vs-yield, production breakdown, yield distribution, and five-year trend.",
    url: dashboardPngUrl,
    icon: <ImageIcon />,
  },
  {
    name: "agri_risk_map.html",
    desc: "Self-contained Folium HTML map with score-scaled markers and a toggleable water-stress overlay — open in any browser.",
    url: riskMapHtmlUrl,
    icon: <MapIcon />,
  },
];

export default function OutputsPanel() {
  return (
    <section id="outputs">
      <div className="section-head">
        <div>
          <div className="section-eyebrow">Outputs</div>
          <h2>Downloadable artefacts from every task</h2>
        </div>
        <p className="section-desc">
          Each file is generated by the FastAPI pipeline at refresh time. Use them directly
          in your evaluation notebook or open in-browser.
        </p>
      </div>

      <div className="outputs-grid">
        {DOWNLOADS.map((d) => (
          <div className="download-card" key={d.name}>
            <div className="download-icon">{d.icon}</div>
            <div className="download-name">{d.name}</div>
            <p className="download-desc">{d.desc}</p>
            <a className="download-btn" href={d.url} target="_blank" rel="noreferrer">
              <DownloadIcon /> Download
            </a>
          </div>
        ))}
      </div>
    </section>
  );
}
