"""
FastAPI entrypoint for the Smart Agriculture & Crop Analytics platform.

Wires together the four task modules (ETL, ranking, dashboard, risk map)
behind a REST API consumed by the React frontend, and serves the raw
deliverable files (CSV / PNG / HTML) generated by each task.
"""
from __future__ import annotations

import logging
from contextlib import asynccontextmanager
from typing import Optional

from dotenv import load_dotenv
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

# Configure logging to see debug messages
logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)

# Load .env BEFORE importing modules that read env vars at import time.
load_dotenv()

from app.chatbot.chat import (
    GroqAPIError,
    GroqConfigError,
    build_context_summary,
    chat_with_groq,
)
from app.task1_etl.etl import OUTPUT_DIR, run_etl
from app.task2_ranking.ranking import binary_search_state, rank_states
from app.task3_dashboard.dashboard import build_dashboard_payload, render_dashboard_png
from app.task4_riskmap.riskmap import build_riskmap_payload, render_riskmap_html

STATE: dict = {}


def _build_state() -> None:
    """Runs the full task1-4 pipeline once and caches results in memory."""
    df = run_etl()
    ranked = rank_states(df)
    render_dashboard_png(df)
    render_riskmap_html(ranked)

    STATE["dataframe"] = df
    STATE["ranked_states"] = ranked
    STATE["dashboard_payload"] = build_dashboard_payload(df)
    STATE["riskmap_payload"] = build_riskmap_payload(ranked)
    STATE["chatbot_context"] = build_context_summary(
        df, ranked, STATE["dashboard_payload"], STATE["riskmap_payload"]
    )


@asynccontextmanager
async def lifespan(_: FastAPI):
    _build_state()
    yield


app = FastAPI(
    title="Smart Agriculture & Crop Analytics API",
    description="Backend for Tasks 1-4 of the Smart Agriculture hackathon set.",
    version="1.0.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.mount("/outputs", StaticFiles(directory=OUTPUT_DIR), name="outputs")


@app.get("/api/health")
def health_check() -> dict:
    return {"status": "ok"}


@app.post("/api/etl/refresh")
def refresh_pipeline() -> dict:
    """Re-runs the ETL -> ranking -> dashboard -> risk map pipeline."""
    _build_state()
    return {"status": "refreshed", "rows": len(STATE["dataframe"])}


@app.get("/api/etl/summary")
def etl_summary() -> dict:
    df = STATE["dataframe"]
    return {
        "row_count": int(len(df)),
        "state_count": int(df["state"].nunique()),
        "crop_count": int(df["crop"].nunique()),
        "avg_yield_kg_ha": round(float(df["yield_kg_ha"].mean()), 2),
        "avg_irrigation_pct": round(float(df["irrigation_pct"].mean()), 2),
        "total_production_tonnes": round(float(df["total_production_tonnes"].sum()), 2),
        "total_farm_revenue_cr": round(float(df["farm_revenue_cr"].sum()), 2),
        "water_stressed_rows": int(df["Water_Stressed"].sum()),
    }


@app.get("/api/etl/records")
def etl_records() -> list[dict]:
    return STATE["dataframe"].to_dict(orient="records")


@app.get("/api/ranking")
def ranking() -> list[dict]:
    return STATE["ranked_states"]


@app.get("/api/ranking/search")
def ranking_search(state: str = Query(..., description="State name to look up")) -> dict:
    rank = binary_search_state(STATE["ranked_states"], state)
    if rank is None:
        raise HTTPException(status_code=404, detail=f"State '{state}' not found")
    record = next(r for r in STATE["ranked_states"] if r["rank"] == rank)
    return record


@app.get("/api/dashboard")
def dashboard() -> dict:
    return STATE["dashboard_payload"]


@app.get("/api/riskmap")
def riskmap() -> list[dict]:
    return STATE["riskmap_payload"]


@app.get("/api/riskmap/summary")
def riskmap_summary() -> dict:
    markers = STATE["riskmap_payload"]
    return {
        "green": sum(1 for m in markers if m["colour"] == "green"),
        "orange": sum(1 for m in markers if m["colour"] == "orange"),
        "red": sum(1 for m in markers if m["colour"] == "red"),
        "water_stressed": sum(1 for m in markers if m["water_stressed"]),
    }


# --------------------------------------------------------------------------- #
# Chatbot endpoint                                                             #
# --------------------------------------------------------------------------- #
class ChatTurn(BaseModel):
    role: str = Field(..., pattern="^(user|assistant)$")
    content: str


class ChatRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=2000)
    history: list[ChatTurn] = Field(default_factory=list)


class ChatResponse(BaseModel):
    reply: str
    model: str


@app.post("/api/chat", response_model=ChatResponse)
def chat(req: ChatRequest) -> ChatResponse:
    """Answer a user question grounded in the cached pipeline context."""
    context = STATE.get("chatbot_context")
    if not context:
        raise HTTPException(
            status_code=503,
            detail="Pipeline not ready yet. Try again in a moment.",
        )
    try:
        reply = chat_with_groq(
            question=req.message,
            context_summary=context,
            history=[t.model_dump() for t in req.history],
        )
    except GroqConfigError as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc
    except GroqAPIError as exc:
        raise HTTPException(status_code=502, detail=str(exc)) from exc

    from app.chatbot.chat import GROQ_MODEL
    return ChatResponse(reply=reply, model=GROQ_MODEL)
